### ISSUE TITLE
Question: Cannot have an empty ID at the root of a window

### ISSUE THREAD

**Issue by VaclavElias** [HexaEngine/Hexa.NET.ImGui#33] opened 2024-12-15 01:41 UTC
Hi, I wonder if you would know, why are we getting this error? If we use 2.1.9, all is ok, if we use any higher version or the newest 2.2.4, we get this below.

`Assertion failed: id != window->ID && "Cannot have an empty ID at the root of a window. If you need an empty label, use ## and read the FAQ about how the ID Stack works!", file D:\a\Hexa.NET.ImGui\Hexa.NET.ImGui\cimgui\imgui\imgui.cpp, line 11471`

https://github.com/stride3d/stride-community-toolkit/issues/177

Thank you.

**Comment by JunaMeinhold** [comment] 2024-12-15 08:15
Hi,

that means you have somewhere a ID issue, like you can't use "" and have to use "##9462" or some other id everything after the ## is not shown in texts, also there is a way to suppress it in ImGuiIO.ConfigErrorRecoveryEnableAssert = 0; but i advice to fix it correctly via the id thing or using id push and pop.

**Comment by JunaMeinhold** [comment] 2024-12-16 12:54
I noticed that some of your stuff is also wrong like the signature of the delegates for get and set clipboards are wrong, i provide them via PlatformGetClipboardTextFn and PlatformSetClipboardTextFn

**Comment by VaclavElias** [comment] 2024-12-16 13:13
Thanks for this. I will speak for a fellow contributor to follow up on your suggestions here 🙂

**Comment by JunaMeinhold** [comment] 2024-12-16 13:39
I investigated a bit and found that the issue is here
![image](https://github.com/user-attachments/assets/d523dd79-9f6d-4d23-a13d-e7f4dca85e4b)


Tip: enable mixed mode debugging then those exceptions will show
![image](https://github.com/user-attachments/assets/91e104cf-1d37-43bc-9833-81ccb26e3aff)
![image](https://github.com/user-attachments/assets/e3273156-347d-4c5b-978a-6b6b198befa8)

**Comment by Doprez** [comment] 2024-12-17 18:56
Thanks a ton for that check box! It kept throwing elsewhere without it which was a pain to debug. A bit embarrassing to see that the [issue](https://github.com/stride3d/stride-community-toolkit/blob/000ace2e72bf2b96bf50e3c810ee3c07cf2011ab/src/Stride.CommunityToolkit.ImGui/PerfMonitor.cs#L203) was so obvious now though lol.

I also found another issue with delta time being zero but I think that's a Stride startup issue. I already have a work around but I may need to start the `GameSystem` a frame later or something for things to initialize.

This should be able to be closed as resolved though. Just by adding unique Ids the problem is gone so I need to fix how we handle labels likely with push and pop like you mentioned.

**Comment by JunaMeinhold** [comment] 2024-12-17 19:26
The simplest way would be to just do ##0 ##1 ##2 etc even hardcoded when you are not in a for loop

Like
PlotLines("##0",...)
PlotLines("##1",...)

**Comment by JunaMeinhold** [comment] 2024-12-17 19:41
And also using "Some Label"u8 is faster than without the u8, it bypasses encoding, you can only use u8 on non interpolated strings but should be strictly preferred if applicable.

```
PlotLines("##0"u8,...)

sb.Append("Some Label"u8);
```

**Comment by VaclavElias** [comment] 2024-12-17 23:02
Thank you @JunaMeinhold. @Doprez, shall we close this?

**Comment by Doprez** [comment] 2024-12-17 23:04
The main issue is good to go and was just a missed label in our implementation.

I referenced this issue in another one for the toolkit repo just for the extra fixes we will have to add.

**Closed** 2024-12-17 23:08 UTC
